// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].put').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.post').default>>>>
    }
    '/api/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session.get').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users').default>>>>
    }
    '/auth/github': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/github').default>>>>
    }
    '/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/login.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/login').default>>>>
    }
    '/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/logout.post').default>>>>
    }
    '/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/register.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
  }
}
export {}